repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.6 
  hooks:
    # Run linter
    - id: ruff
    # with --fix
      args: [ --fix ]
    # Run formatter
    # - id: ruff-format

- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
    - id: black